gmis:
  log:
    enabled: false

spring:
  autoconfigure:
    # cao，升级到1.2.0后，gateway要排除这个依赖，排查了2个小时 2020年04月21日00:51:18
    exclude: io.seata.integration.http.HttpAutoConfiguration
  cloud:
    gateway:
      x-forwarded:
        prefixEnabled: false
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true
      routes:
        - id: oauth
          uri: lb://gmis-oauth-server
          predicates:
            - Path=/oauth/**
          filters:
            - StripPrefix=1
            - name: Hystrix
              args:
                name: default
                fallbackUri: 'forward:/fallback'
        - id: file
          uri: lb://gmis-file-server
          predicates:
            - Path=/file/**
          filters:
            - StripPrefix=1
            - name: Hystrix
              args:
                name: default
                fallbackUri: 'forward:/fallback'
        - id: authority
          uri: lb://gmis-authority-server
          predicates:
            - Path=/authority/**
          filters:
            - StripPrefix=1
            - name: Hystrix
              args:
                name: default
                fallbackUri: 'forward:/fallback'
        - id: msgs
          uri: lb://gmis-msgs-server
          predicates:
            - Path=/msgs/**
          filters:
            - StripPrefix=1
            - name: Hystrix
              args:
                name: default
                fallbackUri: 'forward:/fallback'
        - id: demo
          uri: lb://gmis-demo-server
          predicates:
            - Path=/demo/**
          filters:
            - StripPrefix=1
            - name: Hystrix
              args:
                name: default
                fallbackUri: 'forward:/fallback'
        - id: order
          uri: lb://gmis-order-server
          predicates:
            - Path=/order/**
          filters:
            - StripPrefix=1
            - name: Hystrix
              args:
                name: default
                fallbackUri: 'forward:/fallback'
        - id: admincenter
          uri: lb://gmis-admincenter-server
          predicates:
            - Path=/admincenter/**
          filters:
            - StripPrefix=1
            - name: Hystrix
              args:
                name: default
                fallbackUri: 'forward:/fallback'
filters:
  - name: Hystrix
    args:
      name: default
      fallbackUri: 'forward:/fallback'


server:
  port: 8760
  servlet:
    context-path: /api  # = server.servlet.context-path
